import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { apiClient } from "@/lib/api-client"
import { queryKeys } from "@/lib/query-keys"
import type { ApiResponse } from "@/types/api"

// 비용 레코드 타입
export interface CostRecord {
  id: string
  date: string
  title: string
  amount: number
  description: string | null
  isAutoGenerated: boolean
  userName: string
}

// 비용 생성/수정 입력 타입
export interface CostInput {
  date: string
  title: string
  amount: number
  description?: string
}

/**
 * 비용 목록 조회 훅
 */
export function useCosts(year: number, month: number) {
  return useQuery({
    queryKey: [...queryKeys.costs, { year, month }],
    queryFn: async () => {
      const params = new URLSearchParams({
        year: String(year),
        month: String(month),
      })
      const response = await apiClient<
        ApiResponse<{ records: CostRecord[]; summary: { totalCosts: number; count: number } }>
      >(`/api/admin/costs?${params.toString()}`)
      return response.data
    },
  })
}

/**
 * 비용 생성 훅
 */
export function useCreateCost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (data: CostInput) => {
      return await apiClient("/api/admin/costs", {
        method: "POST",
        json: data,
      })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.costs })
      queryClient.invalidateQueries({ queryKey: queryKeys.dashboard })
      queryClient.invalidateQueries({ queryKey: queryKeys.dailyCost })
    },
  })
}

/**
 * 비용 수정 훅
 */
export function useUpdateCost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async ({ id, ...data }: CostInput & { id: string }) => {
      return await apiClient(`/api/admin/costs/${id}`, {
        method: "PUT",
        json: data,
      })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.costs })
      queryClient.invalidateQueries({ queryKey: queryKeys.dashboard })
      queryClient.invalidateQueries({ queryKey: queryKeys.dailyCost })
    },
  })
}

/**
 * 비용 삭제 훅
 */
export function useDeleteCost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (id: string) => {
      return await apiClient(`/api/admin/costs/${id}`, {
        method: "DELETE",
      })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.costs })
      queryClient.invalidateQueries({ queryKey: queryKeys.dashboard })
      queryClient.invalidateQueries({ queryKey: queryKeys.dailyCost })
    },
  })
}
