// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI(마이그레이션)는 세션 모드(DIRECT_URL), 없으면 DATABASE_URL 폴백
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
