import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

// 고정폭 글꼴(Geist Mono)은 화면에서 쓰지 않아 제거 (모든 페이지에서 폰트 파일을 미리 받던 비용 절감)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased min-w-[360px]`}
      >
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
